"""campo valor da transacao na tabela log balance

Revision ID: 02913f0f3d69
Revises: 516702bce0cf
Create Date: 2023-12-13 23:53:12.674783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02913f0f3d69'
down_revision: Union[str, None] = '516702bce0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('transaction_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_user_balance', 'transaction_value')
    # ### end Alembic commands ###
