"""alteracao campo fk

Revision ID: 3e81cbd10ce4
Revises: 02913f0f3d69
Create Date: 2023-12-14 01:05:03.950469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e81cbd10ce4'
down_revision: Union[str, None] = '02913f0f3d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('balance_id', sa.Integer(), nullable=True))
    op.drop_index('ix_log_user_balance_user_balance_id', table_name='log_user_balance')
    op.create_index(op.f('ix_log_user_balance_balance_id'), 'log_user_balance', ['balance_id'], unique=False)
    op.drop_constraint('log_user_balance_user_balance_id_fkey', 'log_user_balance', type_='foreignkey')
    op.create_foreign_key(None, 'log_user_balance', 'user_balance', ['balance_id'], ['id'])
    op.drop_column('log_user_balance', 'user_balance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('user_balance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'log_user_balance', type_='foreignkey')
    op.create_foreign_key('log_user_balance_user_balance_id_fkey', 'log_user_balance', 'user_balance', ['user_balance_id'], ['id'])
    op.drop_index(op.f('ix_log_user_balance_balance_id'), table_name='log_user_balance')
    op.create_index('ix_log_user_balance_user_balance_id', 'log_user_balance', ['user_balance_id'], unique=False)
    op.drop_column('log_user_balance', 'balance_id')
    # ### end Alembic commands ###
