"""campo type na tabela log user balance

Revision ID: 516702bce0cf
Revises: 5c1affe22e6a
Create Date: 2023-12-13 23:20:26.313587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516702bce0cf'
down_revision: Union[str, None] = '5c1affe22e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_user_balance', 'type')
    # ### end Alembic commands ###
