"""campo na user: profile; campo na LogUserBalance: month

Revision ID: 5c1affe22e6a
Revises: bb6f1ccdfcd3
Create Date: 2023-12-13 23:03:19.480121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1affe22e6a'
down_revision: Union[str, None] = 'bb6f1ccdfcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('month', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    op.drop_column('log_user_balance', 'month')
    # ### end Alembic commands ###
