"""rename campo month

Revision ID: a1da3244af52
Revises: 3e81cbd10ce4
Create Date: 2023-12-14 01:08:02.070254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1da3244af52'
down_revision: Union[str, None] = '3e81cbd10ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('month_and_year', sa.String(), nullable=True))
    op.drop_column('log_user_balance', 'month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_user_balance', sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('log_user_balance', 'month_and_year')
    # ### end Alembic commands ###
