"""tabela de saldo e log do saldo

Revision ID: bb6f1ccdfcd3
Revises: 807d42b8785f
Create Date: 2023-12-13 21:38:31.893367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6f1ccdfcd3'
down_revision: Union[str, None] = '807d42b8785f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balance_id'), 'user_balance', ['id'], unique=False)
    op.create_index(op.f('ix_user_balance_user_id'), 'user_balance', ['user_id'], unique=False)
    op.create_table('log_user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_balance_id', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['user_balance_id'], ['user_balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_user_balance_id'), 'log_user_balance', ['id'], unique=False)
    op.create_index(op.f('ix_log_user_balance_user_balance_id'), 'log_user_balance', ['user_balance_id'], unique=False)
    op.add_column('user', sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('status', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'dat_edicao')
    op.drop_column('user', 'dat_insercao')
    op.drop_index(op.f('ix_log_user_balance_user_balance_id'), table_name='log_user_balance')
    op.drop_index(op.f('ix_log_user_balance_id'), table_name='log_user_balance')
    op.drop_table('log_user_balance')
    op.drop_index(op.f('ix_user_balance_user_id'), table_name='user_balance')
    op.drop_index(op.f('ix_user_balance_id'), table_name='user_balance')
    op.drop_table('user_balance')
    # ### end Alembic commands ###
