"""criacao de tabelas

Revision ID: fc04e29fefd1
Revises: 
Create Date: 2023-12-17 14:57:27.545466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc04e29fefd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment', sa.String(), nullable=True),
    sa.Column('initial_value', sa.Float(), nullable=True),
    sa.Column('delivery_value', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_balance_id'), 'user_balance', ['id'], unique=False)
    op.create_index(op.f('ix_user_balance_user_id'), 'user_balance', ['user_id'], unique=False)
    op.create_table('log_user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('transaction_value', sa.Float(), nullable=True),
    sa.Column('month_and_year', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['user_balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_user_balance_balance_id'), 'log_user_balance', ['balance_id'], unique=False)
    op.create_index(op.f('ix_log_user_balance_id'), 'log_user_balance', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('dat_insercao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('dat_edicao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='true', nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_log_user_balance_id'), table_name='log_user_balance')
    op.drop_index(op.f('ix_log_user_balance_balance_id'), table_name='log_user_balance')
    op.drop_table('log_user_balance')
    op.drop_index(op.f('ix_user_balance_user_id'), table_name='user_balance')
    op.drop_index(op.f('ix_user_balance_id'), table_name='user_balance')
    op.drop_table('user_balance')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
